# Generated by Django 5.1 on 2024-08-14 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_created_by(apps, schema_editor):
    Donor = apps.get_model('donors', 'Donor')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    default_user = User.objects.first()
    for donor in Donor.objects.all():
        donor.created_by = default_user
        donor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_created_by),
        migrations.AlterField(
            model_name='donor',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE),
        ),
    ]