# Generated by Django 5.1 on 2024-08-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_last_donated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
