# Generated by Django 5.1 on 2024-08-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_notification_donor_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
