# Generated by Django 5.1 on 2024-08-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_notification_is_accepted_notification_is_declined'),
        ('request', '0006_recentreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blood_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='request.bloodrequest'),
        ),
    ]
