# Generated by Django 5.1 on 2024-08-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_alter_notification_blood_request'),
        ('request', '0006_recentreceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='request.bloodrequest'),
        ),
    ]
