# Generated by Django 5.1 on 2024-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_alter_notification_blood_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='blood_request',
        ),
    ]
