# Generated by Django 5.1 on 2024-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
