# Generated by Django 5.1 on 2024-08-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_bloodrequest_requester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
