# Generated by Django 5.1 on 2024-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_bloodrequest_fulfilled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
