# Generated by Django 5.1 on 2024-08-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_donor_created_by_alter_donor_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
